version: '3.6'

volumes:
  redis:

services:
  webapp:
    build: .
    ports:
      - "127.0.0.1:8080:8000"
    volumes:
      - $PWD/..:/srv/gitlog
    command: ["python", "/srv/gitlog/webapp/web/manage.py", "runserver", "0:8000"]
    depends_on: 
      - redis
  redis:
    image: redis:5.0
    volumes:
      - redis:/data

